const test = require('node:test');
const assert = require('node:assert/strict');
const { validateApplication, enrichApplication, normalizePhone } = require('../api/_lib/supplier-programme');

function base(overrides = {}) {
  return {applicationId:'KSP-20260904-ABC12345',language:'en',localeCode:'spoofed',languageExperience:'spoofed',localizationVersion:'spoofed',workingCapital:'yes',purposes:['raw_materials'],companyName:'Acme Precision',manufacturingDescription:'Precision turned parts',state:'Tamil Nadu',city:'Chennai',fundingAmountInr:5000000,orderStatus:'confirmed_po',contactName:'Test Applicant',whatsapp:'98402 47729',consent:true,consentVersion:'supplier-programme-2026-09-v2',schemaVersion:'supplier-programme.v2',...overrides};
}

test('normalizes Indian mobile numbers',()=>assert.equal(normalizePhone('+91 98402 47729'),'+919840247729'));
test('accepts a complete working-capital application and owns locale metadata on the server',()=>{const result=validateApplication(base());assert.equal(result.ok,true);assert.equal(result.data.fundingAmountInr,5000000);assert.equal(result.data.workingCapital,true);assert.equal(result.data.localeCode,'en-IN');assert.equal(result.data.languageExperience,'full-form');assert.equal(result.data.localizationVersion,'supplier-locales.2026-09-05.v1');assert.equal(result.data.schemaVersion,'supplier-programme.v2');assert.equal(result.data.consentVersion,'supplier-programme-2026-09-v2')});
test('accepts every approved launch language as a full application',()=>{for(const language of ['en','hi','mr','gu','ta']){const result=validateApplication(base({language}));assert.equal(result.ok,true,language);assert.equal(result.data.languageExperience,'full-form',language)}});
test('requires amount and demand state for working-capital applications',()=>{const result=validateApplication(base({fundingAmountInr:null,orderStatus:''}));assert.equal(result.ok,false);assert.ok(result.errors.includes('fundingAmountInr'));assert.ok(result.errors.includes('orderStatus'))});
test('captures a non-working-capital enquiry without finance fields',()=>{const result=validateApplication(base({workingCapital:'no',purposes:[],state:'',city:'',fundingAmountInr:null,orderStatus:''}));assert.equal(result.ok,true);assert.equal(result.data.fundingAmountInr,null);assert.equal(enrichApplication(result.data).route,'non-working-capital')});
test('supports the shortened scheduled-language contact flow',()=>{const result=validateApplication(base({language:'as',workingCapital:'',purposes:[],state:'',city:'',fundingAmountInr:null,orderStatus:''}));assert.equal(result.ok,true);assert.equal(result.data.languageExperience,'contact-flow');assert.equal(enrichApplication(result.data).route,'language-follow-up')});
test('routes every non-launch scheduled language to contact flow',()=>{for(const language of ['te','kn','bn','pa','ml','or','as','brx','doi','ks','gom','mai','mni','ne','sa','sat','sd','ur']){const result=validateApplication(base({language,workingCapital:'',purposes:[],state:'',city:'',fundingAmountInr:null,orderStatus:''}));assert.equal(result.ok,true,language);assert.equal(result.data.languageExperience,'contact-flow',language)}});
test('canonicalizes cached Bodo and Konkani language identifiers',()=>{const legacy={workingCapital:'',purposes:[],state:'',city:'',fundingAmountInr:null,orderStatus:'',schemaVersion:'supplier-programme.v1',consentVersion:'supplier-programme-2026-09-v1'};assert.equal(validateApplication(base({language:'bo',...legacy})).data.language,'brx');assert.equal(validateApplication(base({language:'kok',...legacy})).data.language,'gom')});
test('keeps invoice finance and no-order working-capital cases valid',()=>{assert.equal(validateApplication(base({purposes:['invoice_gap'],orderStatus:'no_order'})).ok,true)});
test('accepts legacy capex from cached v1 clients but not from v2',()=>{assert.equal(validateApplication(base({purposes:['capex'],schemaVersion:'supplier-programme.v1',consentVersion:'supplier-programme-2026-09-v1'})).ok,true);const current=validateApplication(base({purposes:['capex']}));assert.equal(current.ok,false);assert.ok(current.errors.includes('purposes'))});
test('rejects a v2 submission carrying the wrong consent contract',()=>{const result=validateApplication(base({consentVersion:'supplier-programme-2026-09-v1'}));assert.equal(result.ok,false);assert.ok(result.errors.includes('consentVersion'))});
test('rejects consent, phone and client-reference failures',()=>{const result=validateApplication(base({consent:false,whatsapp:'123',applicationId:'bad'}));assert.equal(result.ok,false);assert.deepEqual(new Set(result.errors),new Set(['applicationId','whatsapp','consent']))});
test('creates exact response-clock timestamps',()=>{const data=validateApplication(base()).data;const record=enrichApplication(data,new Date('2026-09-04T12:00:00.000Z'));assert.equal(record.reminderAt,'2026-09-05T06:00:00.000Z');assert.equal(record.escalationAt,'2026-09-05T10:00:00.000Z');assert.equal(record.responseDueAt,'2026-09-05T12:00:00.000Z')});
