/**
 * TradeWatch film — canonical shipment data.
 *
 * MIRRORS, VERBATIM, the fixture of record:
 *   sector-watch/platform/backend/tests/fixtures/golden_bundle_v1/
 *   (bundle_data.py · expected_outcomes.json — regenerated by generate.py,
 *    determinism-gated with `generate.py --verify`)
 *
 * This is the ONLY place on-screen values live (Build Bible §2, §6). No value
 * in this file may be duplicated or hardcoded anywhere else in the film.
 * If a value you need is not here, it must land in the fixture first —
 * do not invent it here.
 *
 * The DOCUMENTS array below is machine-emitted from expected_outcomes.json;
 * do not hand-edit field records. Everything is synthetic (no real company,
 * IEC, GSTIN, VAT, vessel, or container).
 */

// ─── types ───────────────────────────────────────────────────────────────────

export interface BBox {
  readonly x0: number;
  readonly y0: number;
  readonly x1: number;
  readonly y1: number;
}

/** One extracted field observation: value + page + bounding box (audit-as-code anchor). */
export interface FieldObservation {
  readonly fieldName: string;
  readonly rawValue: string;
  readonly page: number;
  readonly bbox: BBox;
}

export type DocumentType = "CI" | "PL" | "BL" | "SB" | "CO" | "COI";

/** The four-state readiness vocabulary. Never numeric confidence (Bible §1). */
export type RuleState = "OPEN" | "CONDITIONAL" | "BLOCKED" | "UNCLEAR";

export interface ShipmentDocument {
  readonly assetId: string;
  readonly docKey: string;
  readonly documentType: DocumentType;
  /** Display label per Bible §5 Beat 1. */
  readonly typeLabel: string;
  /** On-screen filename per Bible §5 Beat 1. */
  readonly displayFilename: string;
  /** Path of the rendered PDF inside the fixture. */
  readonly fixtureFilename: string;
  readonly fileSha256: string;
  readonly fields: readonly FieldObservation[];
}

// ─── shipment identity (fixture: bundle_data.py) ─────────────────────────────

export const SHIPMENT = {
  /** Display id (Bible §2; as built in the product demo). */
  displayId: "SHIP-2026-001",
  /** Internal fixture id. */
  shipmentId: "ship.golden.hs850760.in-eu.v1",
  bundleId: "golden_bundle_v1",
  hsCode: "85076000",
  hsDotted: "8507.60.00",
} as const;

// ─── parties (fixture) ───────────────────────────────────────────────────────

export const EXPORTER = {
  name: "Voltcore Energy Cells India Pvt. Ltd.",
  address: ["Plot 14, Chakan Industrial Area, Phase II", "Pune 410501, Maharashtra, India"],
  gstin: "27ABCCV1234F1ZL",
  iec: "ABCCV1234F",
  pan: "ABCCV1234F",
} as const;

export const BUYER = {
  name: "EuroVolt Mobility GmbH",
  address: ["Hafenstrasse 22", "20457 Hamburg, Germany"],
  vat: "DE312345678",
} as const;

/** Manufacturer of record for the cell — the UN 38.3 counterparty (fixture). */
export const CELL_SUPPLIER = {
  name: "Anode Cell Systems Pvt. Ltd.",
  city: "Hosur",
} as const;

// ─── goods and value build-up (fixture) ──────────────────────────────────────

export const GOODS = {
  description: "Lithium-ion battery cells (NMC) 3.7V 5000mAh, EV traction-pack grade",
  quantity: 5000,
  unit: "NOS",
  unitPrice: "USD 12.00",
  incoterm: "CIF Hamburg",
  currency: "USD",
} as const;

export const VALUES = {
  fob: "USD 60,000.00",
  freight: "USD 2,750.00",
  insurancePremium: "USD 313.00",
  cif: "USD 63,063.00",
  /** Exact CIF × 1.10 = 69,369.30; the certificate rounds DOWN to a whole dollar. */
  sumInsuredExact: "USD 69,369.30",
  sumInsuredCertificate: "USD 69,369.00",
  sumInsuredBasis: "CIF + 10%",
} as const;

// ─── the invoice-number trap (fixture seed: sb005_invoice_number_trap) ───────

export const INVOICE_TRAP = {
  /** Raised in Tally: CI + PL + GSTN e-invoice. */
  tally: "EXP/2026/0042",
  /** Re-keyed on the Shipping Bill in ICEGATE hyphen format. */
  icegate: "EXP-2026-0042",
  /** The two characters that differ — isolated on screen in Beat 2. */
  tallySeparator: "/",
  icegateSeparator: "-",
} as const;

// ─── dates (fixture) ─────────────────────────────────────────────────────────

export const DATES = {
  commercialInvoice: "20-Feb-2026",
  shippingBill: "25-Feb-2026",
  blOnBoard: "28-Feb-2026",
  estimatedDelivery: "27-Mar-2026",
} as const;

// ─── transport (fixture) ─────────────────────────────────────────────────────

export const TRANSPORT = {
  originPort: "INNSA",
  originPortName: "Nhava Sheva (JNPT), India",
  destPort: "DEHAM",
  destPortName: "Hamburg, Germany",
  vessel: "MV NORDIC EXPRESS V.214W",
  blNumber: "MAEU-NSAHAM-77310",
  containerNo: "MSKU7731045",
  cooNumber: "COO/IN/2026/55217",
  insuranceCertNo: "MCC/2026/0042",
  rodtepScheme: "RODTEPY",
  iccClauses: "Institute Cargo Clauses (A) 1/1/09; Institute War & Strikes Clauses",
} as const;

// ─── UN 38.3 supplier-loop return payload (fixture: supplier_records) ────────

export const UN38_3 = {
  /** 3.7 V × 5000 mAh = 18.5 Wh — arithmetically consistent with the goods description. */
  wattHoursPerCell: 18.5,
  wattHoursUnit: "Wh",
  testReportReference: "T-2025-11-4471",
  /** On-screen intake filename per Bible §5 Beat 1. */
  displayFilename: "UN38_3_Test_Summary.pdf",
  /** Filename of the PDF the supplier returns, per Bible §5 Beat 4c. */
  returnedFilename: "UN38_3_TestSummary_NMC5000.pdf",
  typeLabel: "UN 38.3 Test Summary",
  /** Number of verified observations the supplier return contributes. */
  fieldCount: 2,
} as const;

// ─── reconciliation verdicts (fixture: expected_reconciliation_verdicts) ─────

export const RECONCILIATION_VERDICTS = [
  {
    ruleId: "rule.icegate.sb005.invoice_number_match",
    sharedFact: "export_invoice_number",
    state: "BLOCKED" as RuleState,
    fired: true,
    detail: "SB EXP-2026-0042 (ICEGATE) != GSTN/CI EXP/2026/0042 (Tally).",
  },
  {
    ruleId: "rule.icegate.sb003.gstin_match",
    sharedFact: "exporter_gstin",
    state: "OPEN" as RuleState,
    fired: false,
    detail: "GSTIN reconciles after case-normalization (SB upper vs GSTN lower).",
  },
  {
    ruleId: "rule.identity.exporter_name_match",
    sharedFact: "exporter_legal_name",
    state: "OPEN" as RuleState,
    fired: false,
    detail: "Exporter name reconciles after loose normalization (both 'Pvt Ltd').",
  },
] as const;

// ─── forward-looking rule states (fixture: expected_rule_states) ─────────────

export const EXPECTED_RULE_STATES = [
  {
    ruleId: "rodtep.rate.hs850760",
    state: "UNCLEAR" as RuleState,
    seedId: "rodtep_february_volatility_window",
  },
  {
    ruleId: "insurance.cif_plus_10_sum_insured",
    state: "CONDITIONAL" as RuleState,
    seedId: "cif_plus_10_rounding_edge",
  },
  {
    ruleId: "cogsa.suit_time_bar",
    state: "OPEN" as RuleState,
    seedId: "cogsa_mtga_time_bar_anchors",
  },
  {
    ruleId: "mtga.suit_time_bar",
    state: "OPEN" as RuleState,
    seedId: "cogsa_mtga_time_bar_anchors",
  },
] as const;

// ─── film display register (Bible §2 and §5 — on-screen values that are not
//     fixture facts; sourced from the locked shot list, never invented) ───────

export const DISPLAY = {
  /** Reviewer of record (Bible §2; as built in the product demo). */
  reviewerOfRecord: "Kavya Reddy",
  /** Short reviewer form used in the Beat 2 override chip (Bible §5). */
  reviewerShort: "K. Reddy",
  /** Approver in the Beat 4b human beat (Bible §5). */
  approver: "A. Sreenath",
  /** Seal hash display string, scrambles then settles (Bible §5 Beat 6). */
  sealHash: "8a7f29c4…b4f6a8",
  /** SB005 chip copy (Bible §5 Beat 2; code + label match the fixture verdict). */
  sb005Chip: "ICEGATE SB005 · Invalid Invoice Number · BLOCKED",
  /** UN 38.3 rule card (Bible §5 Beat 3). */
  ruleCardL2R03: "L2-R03 · Li-ion UN 3480 · IMDG Section IA · Wh-threshold trigger",
} as const;

// ─── the six extracted documents (machine-emitted from expected_outcomes.json;
//     display filenames and type labels per Bible §5 Beat 1) ──────────────────

export const DOCUMENTS = [
  {
    assetId: "asset.golden.ci",
    docKey: "commercial_invoice",
    documentType: "CI",
    typeLabel: "Commercial Invoice",
    displayFilename: "Commercial_Invoice_EXP-2026-0042.pdf",
    fixtureFilename: "documents/01_commercial_invoice.pdf",
    fileSha256: "e80390262f66eeee6f514f4bf215217118ae41571316379ad829c26eb9e5da0f",
    fields: [
      { fieldName: "invoice_number", rawValue: "EXP/2026/0042", page: 1, bbox: { x0: 250.0, y0: 617.2, x1: 320.2, y1: 624.58 } },
      { fieldName: "invoice_date", rawValue: "20-Feb-2026", page: 1, bbox: { x0: 250.0, y0: 601.2, x1: 309.4, y1: 608.58 } },
      { fieldName: "exporter_gstin", rawValue: "27ABCCV1234F1ZL", page: 1, bbox: { x0: 250.0, y0: 585.2, x1: 331.0, y1: 592.58 } },
      { fieldName: "exporter_iec", rawValue: "ABCCV1234F", page: 1, bbox: { x0: 250.0, y0: 569.2, x1: 304.0, y1: 576.58 } },
      { fieldName: "incoterm", rawValue: "CIF Hamburg", page: 1, bbox: { x0: 250.0, y0: 553.2, x1: 309.4, y1: 560.58 } },
      { fieldName: "hs_code", rawValue: "8507.60.00", page: 1, bbox: { x0: 250.0, y0: 531.2, x1: 304.0, y1: 538.58 } },
      { fieldName: "goods_description", rawValue: "Lithium-ion battery cells (NMC) 3.7V 5000mAh, EV traction-pack grade", page: 1, bbox: { x0: 60.0, y0: 502.2, x1: 427.2, y1: 509.58 } },
      { fieldName: "quantity", rawValue: "5000 NOS", page: 1, bbox: { x0: 250.0, y0: 483.2, x1: 293.2, y1: 490.58 } },
      { fieldName: "unit_price", rawValue: "USD 12.00", page: 1, bbox: { x0: 250.0, y0: 467.2, x1: 298.6, y1: 474.58 } },
      { fieldName: "fob_value", rawValue: "USD 60,000.00", page: 1, bbox: { x0: 250.0, y0: 445.2, x1: 320.2, y1: 452.58 } },
      { fieldName: "freight", rawValue: "USD 2,750.00", page: 1, bbox: { x0: 250.0, y0: 429.2, x1: 314.8, y1: 436.58 } },
      { fieldName: "insurance", rawValue: "USD 313.00", page: 1, bbox: { x0: 250.0, y0: 413.2, x1: 304.0, y1: 420.58 } },
      { fieldName: "cif_value", rawValue: "USD 63,063.00", page: 1, bbox: { x0: 250.0, y0: 397.2, x1: 320.2, y1: 404.58 } },
    ],
  },
  {
    assetId: "asset.golden.pl",
    docKey: "packing_list",
    documentType: "PL",
    typeLabel: "Packing List",
    displayFilename: "Packing_List_VOLT-PL-0042.pdf",
    fixtureFilename: "documents/02_packing_list.pdf",
    fileSha256: "b513dfe208e83e22e20bd211a9cc8655a3b5f4b7c1b09c4cc26d5d0399384de8",
    fields: [
      { fieldName: "invoice_number", rawValue: "EXP/2026/0042", page: 1, bbox: { x0: 250.0, y0: 689.2, x1: 320.2, y1: 696.58 } },
      { fieldName: "invoice_date", rawValue: "20-Feb-2026", page: 1, bbox: { x0: 250.0, y0: 673.2, x1: 309.4, y1: 680.58 } },
      { fieldName: "hs_code", rawValue: "8507.60.00", page: 1, bbox: { x0: 250.0, y0: 657.2, x1: 304.0, y1: 664.58 } },
      { fieldName: "quantity", rawValue: "5000 NOS", page: 1, bbox: { x0: 250.0, y0: 603.2, x1: 293.2, y1: 610.58 } },
      { fieldName: "packages", rawValue: "100 cartons", page: 1, bbox: { x0: 250.0, y0: 587.2, x1: 309.4, y1: 594.58 } },
      { fieldName: "net_weight", rawValue: "1,250.000 KGS", page: 1, bbox: { x0: 250.0, y0: 571.2, x1: 320.2, y1: 578.58 } },
      { fieldName: "gross_weight", rawValue: "1,420.000 KGS", page: 1, bbox: { x0: 250.0, y0: 555.2, x1: 320.2, y1: 562.58 } },
      { fieldName: "dimensions", rawValue: "100 x (40 x 30 x 25) cm", page: 1, bbox: { x0: 250.0, y0: 539.2, x1: 374.2, y1: 546.58 } },
    ],
  },
  {
    assetId: "asset.golden.bl",
    docKey: "bill_of_lading",
    documentType: "BL",
    typeLabel: "Bill of Lading",
    displayFilename: "BL_MAEU-NSAHAM-77310.pdf",
    fixtureFilename: "documents/03_bill_of_lading.pdf",
    fileSha256: "e36c483a06977fade25d8e097f5146d7a7227f5b0c45358743afa48509021b13",
    fields: [
      { fieldName: "bl_number", rawValue: "MAEU-NSAHAM-77310", page: 1, bbox: { x0: 250.0, y0: 748.2, x1: 341.8, y1: 755.58 } },
      { fieldName: "vessel", rawValue: "MV NORDIC EXPRESS V.214W", page: 1, bbox: { x0: 250.0, y0: 732.2, x1: 379.6, y1: 739.58 } },
      { fieldName: "port_of_loading", rawValue: "Nhava Sheva (JNPT), India (INNSA)", page: 1, bbox: { x0: 250.0, y0: 592.2, x1: 428.2, y1: 599.58 } },
      { fieldName: "port_of_discharge", rawValue: "Hamburg, Germany (DEHAM)", page: 1, bbox: { x0: 250.0, y0: 576.2, x1: 379.6, y1: 583.58 } },
      { fieldName: "container_no", rawValue: "MSKU7731045", page: 1, bbox: { x0: 250.0, y0: 560.2, x1: 309.4, y1: 567.58 } },
      { fieldName: "shipped_on_board_date", rawValue: "28-Feb-2026", page: 1, bbox: { x0: 250.0, y0: 544.2, x1: 309.4, y1: 551.58 } },
      { fieldName: "estimated_delivery_date", rawValue: "27-Mar-2026", page: 1, bbox: { x0: 250.0, y0: 528.2, x1: 309.4, y1: 535.58 } },
      { fieldName: "goods_description", rawValue: "100 cartons lithium-ion battery cells", page: 1, bbox: { x0: 250.0, y0: 506.2, x1: 449.8, y1: 513.58 } },
      { fieldName: "gross_weight", rawValue: "1,420.000 KGS", page: 1, bbox: { x0: 250.0, y0: 490.2, x1: 320.2, y1: 497.58 } },
    ],
  },
  {
    assetId: "asset.golden.sb",
    docKey: "shipping_bill_draft",
    documentType: "SB",
    typeLabel: "Shipping Bill (draft)",
    displayFilename: "SB_Draft_INNSA_2026-02-25.pdf",
    fixtureFilename: "documents/04_shipping_bill_draft.pdf",
    fileSha256: "113de038b18927370500f80499c8c506a398365b2a5abf243c44e55ad82a790c",
    fields: [
      { fieldName: "invoice_number", rawValue: "EXP-2026-0042", page: 1, bbox: { x0: 250.0, y0: 748.2, x1: 320.2, y1: 755.58 } },
      { fieldName: "sb_date", rawValue: "25-Feb-2026", page: 1, bbox: { x0: 250.0, y0: 732.2, x1: 309.4, y1: 739.58 } },
      { fieldName: "exporter_name", rawValue: "VOLTCORE ENERGY CELLS INDIA PVT. LTD.", page: 1, bbox: { x0: 250.0, y0: 716.2, x1: 449.8, y1: 723.58 } },
      { fieldName: "exporter_gstin", rawValue: "27ABCCV1234F1ZL", page: 1, bbox: { x0: 250.0, y0: 700.2, x1: 331.0, y1: 707.58 } },
      { fieldName: "exporter_iec", rawValue: "ABCCV1234F", page: 1, bbox: { x0: 250.0, y0: 684.2, x1: 304.0, y1: 691.58 } },
      { fieldName: "port_code", rawValue: "INNSA", page: 1, bbox: { x0: 250.0, y0: 668.2, x1: 277.0, y1: 675.58 } },
      { fieldName: "hs_code", rawValue: "85076000", page: 1, bbox: { x0: 250.0, y0: 652.2, x1: 293.2, y1: 659.58 } },
      { fieldName: "quantity", rawValue: "5000 NOS", page: 1, bbox: { x0: 250.0, y0: 636.2, x1: 293.2, y1: 643.58 } },
      { fieldName: "fob_value", rawValue: "USD 60,000.00", page: 1, bbox: { x0: 250.0, y0: 620.2, x1: 320.2, y1: 627.58 } },
      { fieldName: "scheme_code", rawValue: "RODTEPY", page: 1, bbox: { x0: 250.0, y0: 604.2, x1: 287.8, y1: 611.58 } },
    ],
  },
  {
    assetId: "asset.golden.co",
    docKey: "certificate_of_origin",
    documentType: "CO",
    typeLabel: "Certificate of Origin",
    displayFilename: "COO_IN_2026_55217.pdf",
    fixtureFilename: "documents/05_certificate_of_origin.pdf",
    fileSha256: "1298d618e22f8703e162698b97948a7b1aec1cd773e870c01272e2814b2db6ff",
    fields: [
      { fieldName: "coo_number", rawValue: "COO/IN/2026/55217", page: 1, bbox: { x0: 250.0, y0: 748.2, x1: 341.8, y1: 755.58 } },
      { fieldName: "country_of_origin", rawValue: "INDIA", page: 1, bbox: { x0: 250.0, y0: 608.2, x1: 277.0, y1: 615.58 } },
      { fieldName: "invoice_number", rawValue: "EXP/2026/0042", page: 1, bbox: { x0: 250.0, y0: 592.2, x1: 320.2, y1: 599.58 } },
      { fieldName: "hs_code", rawValue: "8507.60.00", page: 1, bbox: { x0: 250.0, y0: 576.2, x1: 304.0, y1: 583.58 } },
      { fieldName: "quantity", rawValue: "5000 NOS", page: 1, bbox: { x0: 250.0, y0: 560.2, x1: 293.2, y1: 567.58 } },
    ],
  },
  {
    assetId: "asset.golden.coi",
    docKey: "marine_insurance_certificate",
    documentType: "COI",
    typeLabel: "Insurance Certificate",
    displayFilename: "COI_MCC_2026_0042.pdf",
    fixtureFilename: "documents/06_marine_insurance_certificate.pdf",
    fileSha256: "0af6316faed178ce3b799ba54dd1423d1cdbef3ca32bfda2b114046568c10db4",
    fields: [
      { fieldName: "cert_number", rawValue: "MCC/2026/0042", page: 1, bbox: { x0: 250.0, y0: 748.2, x1: 320.2, y1: 755.58 } },
      { fieldName: "assured", rawValue: "Voltcore Energy Cells India Pvt. Ltd.", page: 1, bbox: { x0: 250.0, y0: 732.2, x1: 449.8, y1: 739.58 } },
      { fieldName: "invoice_number", rawValue: "EXP/2026/0042", page: 1, bbox: { x0: 250.0, y0: 716.2, x1: 320.2, y1: 723.58 } },
      { fieldName: "voyage", rawValue: "Nhava Sheva (JNPT), India to Hamburg, Germany", page: 1, bbox: { x0: 250.0, y0: 700.2, x1: 493.0, y1: 707.58 } },
      { fieldName: "cif_value", rawValue: "USD 63,063.00", page: 1, bbox: { x0: 250.0, y0: 684.2, x1: 320.2, y1: 691.58 } },
      { fieldName: "sum_insured_basis", rawValue: "CIF + 10%", page: 1, bbox: { x0: 250.0, y0: 668.2, x1: 298.6, y1: 675.58 } },
      { fieldName: "sum_insured", rawValue: "USD 69,369.00", page: 1, bbox: { x0: 250.0, y0: 652.2, x1: 320.2, y1: 659.58 } },
    ],
  },
] as const satisfies readonly ShipmentDocument[];

// ─── derived counts (computed, never hardcoded) ──────────────────────────────

/**
 * Extracted field observations across the six classified documents at intake.
 * Counted from the fixture oracle — NOT the storyboard's "22" or the design
 * doc's "24", which contradict each other (Bible §2). Currently 52.
 */
export const FIELD_COUNT: number = DOCUMENTS.reduce((n, d) => n + d.fields.length, 0);

/** Documents on screen at intake: six classified + the UN 38.3 summary (0 verified). */
export const DOCUMENT_COUNT: number = DOCUMENTS.length + 1;

/** Field observations after the supplier loop closes (Beat 4d adds two). Currently 54. */
export const FIELD_COUNT_AFTER_SUPPLIER_LOOP: number = FIELD_COUNT + UN38_3.fieldCount;
